### ISSUE TITLE
PSQL 9.6 no longer compatible with archlinux.

### ISSUE THREAD

**Issue by Rawleenc** [frealgagu/archlinux.postgresql-9.6#1]
With the release of libldap 2.6 on archlinux's core repository (https://archlinux.org/packages/core/x86_64/libldap/), there is an essential file for psql 9.6 that has been removed : `libldap_r-2.4.so.2`.

So in order for packages of this repository to continue to work, libldap package need to be locked on the latest 2.4 version.

I've also tried to create a symlink named `libldap_r-2.4.so.2` who target `/usr/lib/libldap.so` but it doesn't work.

This will be a big issue for all new archlinux's installations who need to run a psql 9.6 server...

**Comment by frealgagu** [comment]
Seems to be resolved in last version
